# Generated by Django 5.2 on 2025-04-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatlog_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
