# Generated by Django 5.2 on 2025-04-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatbotcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotcategory',
            name='description',
        ),
    ]
