# Generated by Django 5.2 on 2025-04-23 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_chatbotcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatbotcategory'),
        ),
    ]
