# Generated by Django 5.2 on 2025-04-25 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_chatlog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='chatbot.chatbotcategory')),
            ],
        ),
    ]
