# Generated by Django 5.2 on 2025-04-26 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_chatbotsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatbotsubcategory'),
        ),
    ]
