# Generated by Django 5.2 on 2025-04-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_chatlog_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='category',
            field=models.ManyToManyField(blank=True, to='chatbot.chatbotcategory'),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='chatbot.chatbotsubcategory'),
        ),
    ]
