# Generated by Django 5.2 on 2025-05-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_remove_chatlog_category_remove_chatlog_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
