# Generated by Django 5.2 on 2025-05-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_excelfile_qadata_textcontent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qadata',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='qadata',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='chatbot.chatbotsubcategory'),
        ),
        migrations.RemoveField(
            model_name='qadata',
            name='category',
        ),
        migrations.AddField(
            model_name='qadata',
            name='category',
            field=models.ManyToManyField(blank=True, to='chatbot.chatbotcategory'),
        ),
    ]
