# Generated by Django 5.2 on 2025-05-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_remove_qadata_sub_category_qadata_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfile',
            name='title',
        ),
    ]
