# Generated by Django 5.2 on 2025-05-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_remove_excelfile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textcontent',
            name='title',
        ),
    ]
