# Generated by Django 5.2 on 2025-05-15 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_urlmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excels_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='files_upload',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qadata',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qadata_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='urlmodel',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
