# Generated by Django 5.2 on 2025-05-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_chatsession_chatlog_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
