# Generated by Django 5.2 on 2025-05-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_chatlog_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, default='New Chat', max_length=255),
        ),
    ]
