# Generated by Django 5.2 on 2025-06-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_alter_chatsession_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_files', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('excel_files', models.FileField(blank=True, null=True, upload_to='excel/')),
            ],
        ),
    ]
