# Generated by Django 5.2 on 2025-06-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_filedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='doc_files',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='excel_files',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
