# Generated by Django 5.2 on 2025-06-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0021_alter_filedata_doc_files_alter_filedata_excel_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='doc_files',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='excel_files',
            field=models.FileField(blank=True, null=True, upload_to='excel/'),
        ),
    ]
