# Generated by Django 5.2 on 2025-06-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0022_delete_profile_userprofile_chat_history_access_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('sales', 'Sales'), ('non-sales', 'Non-Sales')], max_length=20)),
                ('files_access', models.BooleanField(default=False)),
                ('text_access', models.BooleanField(default=False)),
                ('excel_access', models.BooleanField(default=False)),
                ('qna_access', models.BooleanField(default=False)),
                ('url_access', models.BooleanField(default=False)),
                ('chat_history_access', models.BooleanField(default=False)),
            ],
        ),
    ]
