# Generated by Django 5.2 on 2025-06-02 14:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0022_alter_filedata_doc_files_alter_filedata_excel_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedata',
            name='doc_files',
        ),
        migrations.RemoveField(
            model_name='filedata',
            name='excel_files',
        ),
        migrations.AddField(
            model_name='filedata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='DocumentFileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_files', to='chatbot.filedata')),
            ],
        ),
        migrations.CreateModel(
            name='ExcelFileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_files', to='chatbot.filedata')),
            ],
        ),
    ]
