# Generated by Django 5.2 on 2025-06-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0023_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
