# Generated by Django 5.2 on 2025-06-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0023_remove_filedata_doc_files_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapFetch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('urls', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('error', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
