# Generated by Django 5.2 on 2025-06-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_chatbotinstance'),
        ('chatbot', '0024_sitemapfetch'),
    ]

    operations = [
    ]
