# Generated by Django 5.2 on 2025-06-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0025_merge_0020_chatbotinstance_0024_sitemapfetch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatbotInstance',
        ),
    ]
