# Generated by Django 5.2 on 2025-06-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0027_userprofile_user_details_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_details_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_profile_access',
            field=models.BooleanField(default=False),
        ),
    ]
