# Generated by Django 5.2 on 2025-06-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0028_profile_user_details_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_details_access',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_profile_access',
        ),
    ]
