# Generated by Django 5.2 on 2025-06-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0030_userprofile_user_details_access_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='excelfile',
            name='knowledge_bases',
            field=models.ManyToManyField(blank=True, related_name='excel_documents', to='chatbot.knowledgebase'),
        ),
        migrations.AddField(
            model_name='files_upload',
            name='knowledge_bases',
            field=models.ManyToManyField(blank=True, related_name='files_documents', to='chatbot.knowledgebase'),
        ),
        migrations.AddField(
            model_name='qadata',
            name='knowledge_bases',
            field=models.ManyToManyField(blank=True, related_name='qa_documents', to='chatbot.knowledgebase'),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='knowledge_bases',
            field=models.ManyToManyField(blank=True, related_name='text_documents', to='chatbot.knowledgebase'),
        ),
    ]
