# Generated by Django 5.2 on 2025-06-10 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0031_knowledgebase_excelfile_knowledge_bases_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='files_upload',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/attachments/'),
        ),
        migrations.AddField(
            model_name='files_upload',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='files_upload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='files_upload',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
