# Generated by Django 5.2 on 2025-06-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0032_files_upload_attachment_files_upload_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files_upload',
            name='attachment',
        ),
    ]
