# Generated by Django 5.2 on 2025-06-10 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0036_qadata_description_qadata_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urlmodel',
            name='knowledge_bases',
            field=models.ManyToManyField(blank=True, related_name='url_documents', to='chatbot.knowledgebase'),
        ),
        migrations.AddField(
            model_name='urlmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='urlmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
