# Generated by Django 5.2 on 2025-06-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0037_urlmodel_description_urlmodel_knowledge_bases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='urlmodel',
            name='knowledge_bases',
        ),
        migrations.RemoveField(
            model_name='urlmodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='urlmodel',
            name='updated_by',
        ),
    ]
