# Generated by Django 5.2 on 2025-06-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0039_urlmodel_description_urlmodel_knowledge_bases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='knowledge_bases',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='chatbot.knowledgebase'),
        ),
    ]
