# Generated by Django 5.2 on 2025-06-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0024_sitemapfetch'),
        ('chatbot', '0040_userprofile_knowledge_bases'),
    ]

    operations = [
    ]
