# Generated by Django 5.2 on 2025-06-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0026_delete_chatbotinstance'),
        ('chatbot', '0041_merge_20250613_1625'),
    ]

    operations = [
    ]
