# Generated by Django 5.2 on 2025-06-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0042_merge_20250614_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filedata',
            name='knowledge_bases',
            field=models.ManyToManyField(blank=True, related_name='folder_files', to='chatbot.knowledgebase'),
        ),
    ]
