# Generated by Django 5.2 on 2025-06-14 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0044_filedata_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveFileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleDriveExcelFileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_drive_excel_files', to='chatbot.googledrivefiledata')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleDriveDocumentFileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_drive_document_files', to='chatbot.googledrivefiledata')),
            ],
        ),
    ]
