# Generated by Django 5.2 on 2025-06-16 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0045_googledrivefiledata_googledriveexcelfiledata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='googledrivefiledata',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_drive_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='googledrivefiledata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googledrivefiledata',
            name='knowledge_bases',
            field=models.ManyToManyField(blank=True, related_name='google_drive_files', to='chatbot.knowledgebase'),
        ),
    ]
