# Generated by Django 5.2 on 2025-06-17 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0046_googledrivefiledata_added_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='googledrivefiledata',
            name='relative_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='googledrivefiledata',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='googledrivefiledata',
            name='knowledge_bases',
            field=models.ManyToManyField(blank=True, to='chatbot.knowledgebase'),
        ),
        migrations.AlterField(
            model_name='googledrivefiledata',
            name='mime_type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
