# Generated by Django 5.2 on 2025-07-09 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0048_jogetfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('sheet_names', models.JSONField()),
                ('columns', models.JSONField()),
                ('data_types', models.JSONField()),
                ('sample_rows', models.JSONField()),
                ('row_count', models.JSONField()),
                ('gpt_summary', models.TextField(blank=True, null=True)),
                ('knowledge_base', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_metadata_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
