# Generated by Django 5.2 on 2025-07-09 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0049_excelmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelmetadata',
            name='excel_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata', to='chatbot.excelfile'),
        ),
    ]
