# Generated by Django 5.2 on 2025-07-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0049_profile_ppt_access_userprofile_ppt_access_pptfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ppt_access',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ppt_access',
        ),
        migrations.DeleteModel(
            name='PPTFile',
        ),
    ]
