# Generated by Django 5.2 on 2025-07-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0050_excelmetadata_excel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelmetadata',
            name='key_column_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
