# Generated by Django 5.2 on 2025-07-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0051_profile_ppt_access_userprofile_ppt_access_pptfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pptfile',
            old_name='title',
            new_name='description',
        ),
    ]
