# Generated by Django 5.2 on 2025-07-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0051_excelmetadata_key_column_values'),
        ('chatbot', '0052_rename_title_pptfile_description'),
    ]

    operations = [
    ]
