# Generated by Django 5.2 on 2025-07-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0053_merge_20250709_1255'),
        ('chatbot', '0053_merge_20250709_1731'),
        ('chatbot', '0053_merge_20250710_1656'),
    ]

    operations = [
    ]
