# Generated by Django 5.2 on 2025-07-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0054_merge_20250716_1903'),
        ('chatbot', '0054_merge_20250717_1358'),
    ]

    operations = [
    ]
