# Generated by Django 5.2 on 2025-07-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0055_merge_20250718_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotcategory',
            name='knowledge_bases',
            field=models.ManyToManyField(blank=True, related_name='categories', to='chatbot.knowledgebase'),
        ),
    ]
