# Generated by Django 5.2 on 2025-07-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0056_chatbotcategory_knowledge_bases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotcategory',
            name='knowledge_bases',
        ),
    ]
